[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run --cwd packages/backend build"]

[start]
cmd = "bun run --cwd packages/backend start"
